CREATE TABLE public.sts_foreign_MO
(
    ts timestamp without time zone NOT NULL,
    symbol character varying(7) COLLATE pg_catalog."default",
    total_room numeric,
    owned_ratio numeric,
    curr_room numeric,
    remain_room numeric,
    buy_vol numeric,
    per_buy_vol numeric,
	buy_val numeric,
	per_buy_val numeric,
	sell_vol numeric,
	per_sell_vol numeric,
	sell_val numeric,
	per_sell_val numeric,
	diff_buy_sell_vol numeric,
	diff_buy_sell_val numeric,
	buy_put_vol numeric,
	per_buy_put_vol numeric,
	buy_put_val numeric,
	per_buy_put_val numeric,
	sell_put_vol numeric,
	per_sell_put_vol numeric,
	sell_put_val numeric,
	per_sell_put_val numeric,
	diff_buy_sell_put_vol numeric,
	diff_buy_sell_put_val numeric,
	row numeric
)